
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 20 19:03:33 MDT 2019
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int duracionRecorrido = 29;
  public static final int detectarLinea = 26;
  public static final int resta = 39;
  public static final int suma = 38;
  public static final int punto_medio = 47;
  public static final int decision = 12;
  public static final int colores = 42;
  public static final int llave_c = 36;
  public static final int detener = 20;
  public static final int llave_a = 35;
  public static final int igual = 37;
  public static final int identificador = 40;
  public static final int tiempo = 14;
  public static final int obstaculo = 27;
  public static final int si = 7;
  public static final int esperar = 21;
  public static final int mientras = 11;
  public static final int veloc = 43;
  public static final int energy = 19;
  public static final int op_relacional = 46;
  public static final int importar = 4;
  public static final int velocidad = 13;
  public static final int estadoCamara = 28;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int color = 16;
  public static final int funcion = 5;
  public static final int parentesis_c = 34;
  public static final int falso = 10;
  public static final int parentesis_a = 33;
  public static final int estadoEnergia = 31;
  public static final int avanzar = 18;
  public static final int verdad = 9;
  public static final int detectarColor = 32;
  public static final int regresarBase = 24;
  public static final int detectarAnomalia = 30;
  public static final int time = 44;
  public static final int reversa = 23;
  public static final int separador = 49;
  public static final int detectarParada = 25;
  public static final int inicializacion = 3;
  public static final int alerta = 15;
  public static final int iniciar = 22;
  public static final int detectorParada = 48;
  public static final int caracter_especial = 45;
  public static final int retorno = 6;
  public static final int energia = 17;
  public static final int inicioSecuencia = 2;
  public static final int cadena = 41;
  public static final int sino = 8;
}

