
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 07 11:55:11 MDT 2019
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int duracionRecorrido = 30;
  public static final int detectarLinea = 27;
  public static final int resta = 40;
  public static final int suma = 39;
  public static final int punto_medio = 48;
  public static final int decision = 13;
  public static final int colores = 43;
  public static final int llave_c = 37;
  public static final int detener = 20;
  public static final int llave_a = 36;
  public static final int igual = 38;
  public static final int identificador = 41;
  public static final int tiempo = 15;
  public static final int obstaculo = 28;
  public static final int ubicar = 24;
  public static final int si = 7;
  public static final int esperar = 21;
  public static final int mientras = 11;
  public static final int veloc = 44;
  public static final int op_relacional = 47;
  public static final int importar = 4;
  public static final int velocidad = 14;
  public static final int estadoCamara = 29;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int color = 17;
  public static final int funcion = 5;
  public static final int obtener = 12;
  public static final int parentesis_c = 35;
  public static final int falso = 10;
  public static final int parentesis_a = 34;
  public static final int estadoEnergia = 32;
  public static final int avanzar = 19;
  public static final int verdad = 9;
  public static final int detectarColor = 33;
  public static final int regresarBase = 25;
  public static final int detectarAnomalia = 31;
  public static final int time = 45;
  public static final int reversa = 23;
  public static final int detectarParada = 26;
  public static final int inicializacion = 3;
  public static final int alerta = 16;
  public static final int iniciar = 22;
  public static final int detectorParada = 49;
  public static final int caracter_especial = 46;
  public static final int retorno = 6;
  public static final int energia = 18;
  public static final int inicioSecuencia = 2;
  public static final int cadena = 42;
  public static final int sino = 8;
}

