
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 10 12:59:36 MST 2019
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int duracionRecorrido = 27;
  public static final int detectarLinea = 24;
  public static final int resta = 36;
  public static final int suma = 35;
  public static final int punto_medio = 47;
  public static final int decision = 12;
  public static final int colores = 42;
  public static final int llave_c = 33;
  public static final int detener = 18;
  public static final int llave_a = 32;
  public static final int igual = 34;
  public static final int identificador = 40;
  public static final int tiempo = 14;
  public static final int obstaculo = 25;
  public static final int ide_error = 50;
  public static final int si = 7;
  public static final int esperar = 19;
  public static final int tiempo_error = 55;
  public static final int mientras = 11;
  public static final int veloc = 43;
  public static final int op_relacional = 46;
  public static final int importar = 4;
  public static final int velocidad = 13;
  public static final int estadoCamara = 26;
  public static final int EOF = 0;
  public static final int producto = 37;
  public static final int error = 1;
  public static final int color = 16;
  public static final int funcion = 5;
  public static final int potencia = 39;
  public static final int parentesis_c = 31;
  public static final int caracter_error = 52;
  public static final int falso = 10;
  public static final int parentesis_a = 30;
  public static final int avanzar = 17;
  public static final int verdad = 9;
  public static final int detectarColor = 29;
  public static final int numero_error = 51;
  public static final int regresarBase = 22;
  public static final int detectarAnomalia = 28;
  public static final int color_error = 54;
  public static final int time = 44;
  public static final int reversa = 21;
  public static final int separador = 49;
  public static final int detectarParada = 23;
  public static final int inicializacion = 3;
  public static final int alerta = 15;
  public static final int cadena_error = 53;
  public static final int iniciar = 20;
  public static final int detectorParada = 48;
  public static final int caracter_especial = 45;
  public static final int division = 38;
  public static final int retorno = 6;
  public static final int inicioSecuencia = 2;
  public static final int cadena = 41;
  public static final int sino = 8;
}

